parser: babel-eslint
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended
  - plugin:import/warnings
  - plugin:import/errors
  - plugin:prettier/recommended
plugins:
  - react
  - jsx-a11y
  - import
  - prettier
rules:
  prefer-const: error
  react/prop-types: off
  import/order: error
  prettier/prettier:
    - error
    -
      singleQuote: true
      semi: false
      printWidth: 100
env:
  es6: true
  node: true
  jest: true
  browser: true
parserOptions:
  sourceType: module
  ecmaVersion: 2018
  ecmaFeatures:
    experimentalObjectRestSpread: true
    experimentalDecorators: true
    impliedStrict: true
    classes: true
    jsx: true
